### PR TITLE
Absolute urls for CSS and favicon

### PR DESCRIPTION
**Pull request by Nathan219**
Reduce this to just 1 relative query

### CODE REVIEW

**Comment by anandkumarpatel** [comment]
LGTM

**Comment by anandkumarpatel** [comment]
need to change to for staging though... is that a way to make it dynamic?

**Comment by anandkumarpatel** [comment]
- [x] test on stageing
- [ ] deploy

**Comment by Nathan219** [comment]
https://runnable.io/CodeNow/absolute-link-to-css-and-favicon-detention/
Works on staging.  Defaults to io, but I have it just pulling it's own

**Pull request merged**
